# POST http://localhost:5000/api/auth/login
# Content-Type: application/json

# {
#   "email": "ametsikorbrian@gmail.com",
#   "password": "123brian"
# }

# GET http://localhost:5000/api/protected/dashboard
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2MzOTcyMGViMDE1NDc5YTg4OGY1YzIiLCJlbWFpbCI6ImFtZXRzaWtvcmJyaWFuQGdtYWlsLmNvbSIsImlhdCI6MTc0MDg4MzUyNiwiZXhwIjoxNzQwODg3MTI2fQ.Oo1G1tsboA5-8tm5kt9ijPv1pFHCOb6ezNXZACi8mp4
